### ISSUE TITLE
Trying to apply cost matrix using d_eucl

### ISSUE THREAD

**Issue by proggheli** [lixiaoyu2000/Poly-MOT#26]
Hi!

Im trying to apply d_eucl insted of giou_3d for the first cost metric

I have modified nusc_tracker to the following:
```    def compute_cost(self) -> dict:
        """
        Construct the cost matrix between the trajectory and the detection
        :return: dict, a collection of cost matrices,
        one-stage: np.array, [cls_num, det_num, tra_num], two-stage: np.array, [det_num, tra_num]
        """
        # First step ensures that there are trajectory information
        assert self.tra_infos is not None and self.tra_infos['tra_num'] is not None
        det_num, tra_num = self.det_infos['det_num'], self.tra_infos['tra_num']
        # Variables storing labeles of detection and trajectory information from the last collum of the array and forth from the end for trajectory
        det_labels, tra_labels = self.det_infos['np_dets'][:, -1], self.tra_infos['np_tras'][:, -4]

        # [cls_num, det_num, tra_num], True denotes valid (det label == tra label == cls idx)
        valid_mask = mask_tras_dets(self.cls_num, det_labels, tra_labels)
        tra_cost_infos = {'np_dets': self.tra_infos['np_tras'][:, :-3], 'np_dets_bottom_corners': self.tra_infos['np_tras_bottom_corners']}

        if self.fast:
            # metrics only have giou_3d/giou_bev
            two_cost, first_cost = d_eucl(self.det_infos, tra_cost_infos)
            first_cost = first_cost[None, :, :].repeat(self.cls_num, axis=0)
            first_cost[self.re_metrics['giou_bev']] = two_cost
        else:
            two_cost = globals()[self.second_metric](self.det_infos, tra_cost_infos)
            first_cost = np.zeros((self.cls_num, det_num, tra_num))
            for metric, cls_list in self.re_metrics.items():
                # True denotes invalid(the object's category is not specific)
                tra_cost_infos['mask'] = spec_metric_mask(cls_list, det_labels, tra_labels)
                if metric in METRIC:
                    _, cost1 = globals()[metric](self.det_infos, tra_cost_infos)
                else:
                    cost1 = globals()[metric](self.det_infos, tra_cost_infos)
                first_cost[cls_list] = cost1

        # mask invalid value
        first_cost[np.where(~valid_mask)] = np.inf

        # Due to the execution speed of python,
        # construct the two-stage cost matrix under half-parallel framework is very tricky,
        # we strongly recommend only use giou_bev as two-stage metric to build the cost matrix
        return {'one_stage':first_cost, 'two_stage': 1 - two_cost if two_cost is not None else None}
```
        
And modified the config file to the following:

```
  basic:
  split: 'val'         # dataset split, val/test
  has_velo: False       # whether detector has velo info
  LiDAR_interval: 0.5  # the interval between two adjacent frames of the LiDAR scan, NuScenes: 2HZ
  CLASS_NUM: 7         # number of tracking category, NuScenes: 7

  # CLASS_LABEL: {'bicycle': 0, 
  #               'bus': 1, 
  #               'car': 2, 
  #               'motorcycle': 3, 
  #               'pedestrian': 4, 
  #               'trailer': 5, 
  #               'truck': 6}

preprocessing:
  SF_thre: {0: 0.14, 3: 0.16, 1: 0, 2: 0.16, 5: 0.1, 6: 0, 4: 0.16}
  NMS_thre: 0.08
  NMS_type: blend_nms  # blend_nms, no_blend_nms, blend_soft_nms
  NMS_metric: iou_bev  # iou_bev, iou_3d, giou_bev, giou_3d, d_eucl

association:
  category_metrics: {1: 'giou_bev', 0: 'd_eucl', 2: 'd_eucl', 3: 'd_eucl', 4: 'd_eucl', 5: 'd_eucl', 6: 'd_eucl'}
  second_metric: 'giou_bev'
  two_stage: True  # Whether to use two-stage data association
  first_thre: {1: 1.34, 0: 1.55, 2: 1.31, 3: 1.44, 4: 1.69, 5: 1.25, 6: 1.21}  # category-specific one-stage thresholds
  constant_thre: 1.31
  second_thre: {0: 1.0}  # two-stage thresholds
  algorithm : 'Greedy'  # Greedy, Hungarian, Mutual Nearest Neighbor(MNN)

motion_model:
  # two kalman filter, LinearKalmanFilter, ExtendKalmanFilter
  # filter: {1: 'ExtendKalmanFilter', 0: 'ExtendKalmanFilter', 2: 'ExtendKalmanFilter', 3: 'ExtendKalmanFilter', 4: 'ExtendKalmanFilter', 5: 'ExtendKalmanFilter', 6: 'ExtendKalmanFilter'}
  # five motion model, Linear Model: CV, CA, Non-Linear: CTRA, CTRV, BICYCLE
  # note the consistency of the linear relationship between the model and the filter
  # model: {1: 'CTRA', 0: 'BICYCLE', 2: 'CTRA', 3: 'BICYCLE', 4: 'CTRA', 5: 'CTRA', 6: 'CTRA'}
  filter: {1: 'ExtendKalmanFilter', 0: 'ExtendKalmanFilter', 2: 'ExtendKalmanFilter', 3: 'ExtendKalmanFilter', 4: 'ExtendKalmanFilter', 5: 'LinearKalmanFilter', 6: 'ExtendKalmanFilter'}
  model: {1: 'CTRA', 0: 'BICYCLE', 2: 'CTRA', 3: 'BICYCLE', 4: 'CTRA', 5: 'CA', 6: 'CTRA'}

life_cycle:
  max_age: {1: 10, 0: 10, 2: 15, 3: 20, 4: 10, 5: 10, 6: 20}
  min_hit: {1: 1, 0: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1}
  decay_rate: {0: 0.05, 3: 0.1, 1: 0.3, 2: 0.2, 5: 0.15, 6: 0.25, 4: 0.15}

output:
  punish_num: 1         # The maximum number of predicted frames to write to the output file
  post_nms: False       # whether to use post-nms, this feature is used to reduce FP prediction
  NMS_thre: 0.08
  NMS_type: blend_nms   # blend_nms, no_blend_nms, blend_soft_nms
  NMS_metric: iou_bev   # iou_bev, iou_3d, giou_bev, giou_3d, d_eucl

debug:
  is_debug: true # Whether to debug the code
```
but it gives me this error message:
```
Traceback (most recent call last):
  File "test.py", line 147, in <module>
    main(args.result_path, 0, 1, nusc_loader)
  File "test.py", line 44, in main
    nusc_tracker.tracking(frame_data)
  File "/home/henrik/Poly-MOT-main/tracking/nusc_tracker.py", line 70, in tracking
    dict_track_res = self.tras_update(tracking_ids, data_info)
  File "/home/henrik/Poly-MOT-main/tracking/nusc_tracker.py", line 200, in tras_update
    det_infos=dict_det)
  File "/home/henrik/Poly-MOT-main/tracking/nusc_trajectory.py", line 30, in __init__
    self.motion_management = globals()[KF_type](timestamp, config, track_id, det_infos)
  File "/home/henrik/Poly-MOT-main/motion_module/kalman_filter.py", line 214, in __init__
    self.initialize(det_infos)
  File "/home/henrik/Poly-MOT-main/motion_module/kalman_filter.py", line 226, in initialize
    self.state = self.model.getInitState(det_infos)
  File "/home/henrik/Poly-MOT-main/motion_module/motion_model.py", line 385, in getInitState
    assert q.radians == det_box.yaw
AssertionError
```

Could you help me figure out the issue and how to use d_eucl?

**Comment by lixiaoyu2000** [comment]
Hi, sorry for the late reply. Judging from the error log, your error does not come from modifying the similarity metric, i.e., from `giou` to `d_eucl`. The error comes from the fact that the yaw of `nusc_box` in your detection is inconsistent with the axis angle of the original quaternion. As a reference, you should check the input format of the detector in detail, or debug with a breakpoint at `/home/henrik/Poly-MOT-main/motion_module/motion_model.py`.

**Comment by proggheli** [comment]
Thanks for the respone I will check that, I was wondering if you hade the same threshold for euclidean distance?

**Comment by lixiaoyu2000** [comment]
Hi, the thresholds for euclidean distance are also category-specific. Specifically, we perform the linear search on each category for their matching threshold. We then integrate the best performance parameters of each category in `nusc_config.yaml`.

**Comment by proggheli** [comment]
Okay, Thank you! Do you know if the cordinates from the bounding boxes are in ego or global coordinates?

**Comment by lixiaoyu2000** [comment]
All bounding boxes are defined in the global frame.

**Comment by lixiaoyu2000** [comment]
Issue closed due to inactivaty.
